name: Call CI/CD Workflow With Correct Env

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  run_deployment_workflow_production:
    name: Run Deployment Workflow
    runs-on: ubuntu-latest
    steps: 

      - name: Set environment
        id: env
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "ENVIRONMENT=production" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=development" >> $GITHUB_ENV
          fi

      - name: TEST
        run: |
          ls .github/workflows

    name: Run Deployment Workflow
    uses: ./.github/workflows/deploy-azure-static-web-apps.yml
    with:
      environment: ${{ env.ENVIRONMENT }}
