name: Deploy to Azure

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Environment Variables
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          echo "ENV=prod" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF}" == "refs/heads/staging" ]]; then
          echo "ENV=staging" >> $GITHUB_ENV
        elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          echo "ENV=pr-${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
        fi

    - name: Define Bicep Params
      run: |
        echo "{
          'env': {'value': '$ENV'}
          'location': {'value': 'westeurope'}
        }" > bicep-parameters.json

    - name: Deploy Bicep Template
      id: deploy
      run: |
        az deployment sub create \
          --name Deployment \
          --template-file .azure/main.bicep \                                                                                         
          --parameters bicep-parameters.json \
          --location westeurope

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1

    # - name: Log in to Azure Container Registry
    #   run: |
    #     echo ${{ secrets.AZURE_CLIENT_SECRET }} | docker login $ACR_NAME.azurecr.io --username ${{ secrets.AZURE_CLIENT_ID }} --password-stdin

    # - name: Build and Push Docker Image
    #   id: build-and-push
    #   run: |
    #     docker build -t $ACR_NAME.azurecr.io/my-nextjs-app:${{ github.sha }} .
    #     docker push $ACR_NAME.azurecr.io/my-nextjs-app:${{ github.sha }}
