name: Deploy Azure Static Web Apps CI/CD

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    environment: development
    steps:
      - name: Testing
        run: |
          echo "ENV: ${{ inputs.environment }}"
          echo "TEST_SECRET: ${{ secrets.TEST_SECRET }}"
          echo "all env: ${{ toJSON(secrets) }}"
