on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  run_deployment_workflow_production:
    name: Run Deployment Workflow
    runs-on: ubuntu-latest
    steps: 

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment
        id: env
        run: echo "echo ENVIRONMENT=${{ github.ref == 'refs/heads/main' && 'production' || 'development' }} >> $GITHUB_ENV"

      - name: Deploy to Production
        if: env.ENVIRONMENT == 'production'
        run: .github/workflows/deploy-azure-static-web-apps.yml
        env:
          ENVIRONMENT: production

      - name: Deploy to Development
        if: env.ENVIRONMENT == 'development'
        run: .github/workflows/deploy-azure-static-web-apps.yml
        env:
          ENVIRONMENT: development
