on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  run_deployment_workflow_production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Run Deployment Workflow
    uses: ./deploy-azure-static-web-apps.yml
    with:
      environment: production

  run_deployment_workflow_development:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Run Deployment Workflow
    uses: ./deploy-azure-static-web-apps.yml
    with:
      environment: development

