name: Call CI/CD Workflow With Correct Env

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  set_env:
    name: Set Environment
    id: set_env
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set_env.outputs.ENVIRONMENT }}
    steps: 
      - name: Set environment
        id: set_env
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "ENVIRONMENT=production" >> $GITHUB_OUTPUT
          else
            echo "ENVIRONMENT=development" >> $GITHUB_OUTPUT
          fi

  run_deployment_workflow:
    name: Run Deployment Workflow
    needs: set_env
    uses: ./.github/workflows/deploy-azure-static-web-apps.yml
    with:
      environment: ${{ needs.set_env.outputs.environment }}
