name: Deploy Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  prep:
    outputs:
      isUpload: ${{ steps.step1.outputs.isUpload }}
      env: ${{ steps.step1.outputs.env }}
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "env=production" >> $GITHUB_OUTPUT
          else
            echo "env=development" >> $GITHUB_OUTPUT
          fi
          echo "isUpload=true" >> $GITHUB_OUTPUT

  build_and_deploy_dev:
    needs: prep
    if: |
      ${{ needs.prep.outputs.isUpload }} == true && \
      ${{ needs.prep.outputs.env }} === 'development'
    environment: development
    steps:
      - name: TEST DEV
        run: echo "TEST_SECRET: ${{ secrets.TEST_SECRET }}"

  build_and_deploy_prod:
    needs: prep
    if: |
      ${{ needs.prep.outputs.isUpload }} == true && \
      ${{ needs.prep.outputs.env }} === 'production'
    environment: production
    steps:
      - name: TEST PROD
        run: echo "TEST_SECRET: ${{ secrets.TEST_SECRET }}"

  # build_and_deploy_job:
  #   if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
  #   runs-on: ubuntu-latest
  #   name: Build and Deploy Job
  #   environment: ${{ inputs.environment }}
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: true
  #         lfs: false
  #
  #     - name: Export secrets to .env
  #       run: |
  #         echo "Creating .env file with GitHub Secrets"
  #         secrets=$(echo '${{ toJson(secrets) }}' | jq -r 'to_entries|map("\(.key)=\(.value|tostring|@sh)")|.[]')
  #         echo "$secrets" > .env
  #         cat .env
  #
  #     - name: Build And Deploy
  #       id: builddeploy
  #       uses: Azure/static-web-apps-deploy@v1
  #       with:
  #         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_SKY_01F310E03 }}
  #         repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
  #         action: "upload"
  #         ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
  #         # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
  #         app_location: "/" # App source code path
  #         api_location: "" # Api source code path - optional
  #         output_location: "" # Built app content directory - optional
  #         ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_SKY_01F310E03 }}
          action: "close"
