name: Deploy to Azure

on:
  push:
    branches:
      - main
      - development

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Environment Variables
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          echo "ENV=prod" >> $GITHUB_ENV
          echo "TARGET_RESOURCE_GROUP=${{ secrets.AZURE_PRODUCTION_RESOURCE_GROUP_NAME }}" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF}" == "refs/heads/development" ]]; then
          echo "ENV=dev" >> $GITHUB_ENV
          echo "TARGET_RESOURCE_GROUP=${{ secrets.AZURE_DEVELOPMENT_RESOURCE_GROUP_NAME }}" >> $GITHUB_ENV
        fi
        echo "ACR_NAME=${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}" >> $GITHUB_ENV
        echo "AZURE_SHARED_RESOURCE_GROUP_NAME=${{ secrets.AZURE_SHARED_RESOURCE_GROUP_NAME }}" >> $GITHUB_ENV

    - name: Deploy Bicep Template
      id: deploy
      run: |
        az deployment group create \
          --resource-group $TARGET_RESOURCE_GROUP \
          --template-file .azure/main.bicep

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1

    # - name: Log in to Azure Container Registry
    #   run: |
    #     echo ${{ secrets.AZURE_CLIENT_SECRET }} | docker login $ACR_NAME.azurecr.io --username ${{ secrets.AZURE_CLIENT_ID }} --password-stdin

    # - name: Build and Push Docker Image
    #   id: build-and-push
    #   run: |
    #     docker build -t $ACR_NAME.azurecr.io/my-nextjs-app:${{ github.sha }} .
    #     docker push $ACR_NAME.azurecr.io/my-nextjs-app:${{ github.sha }}
